dist: trusty
sudo: required
language:
  - cpp
compiler:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libstdc++-7-dev
script:
  - g++ -std=c++17 test.cpp 
  - ./a.out -i test3.cpp
